name: assistant
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dropdown_button2: ^2.0.0
  firebase_core: ^2.7.1
  table_calendar: ^3.0.9
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.0.0
  modal_progress_hud_nsn: ^0.3.0
  rflutter_alert: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: lib/assets/fonts/Ubuntu/Ubuntu-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700